### ISSUE TITLE
Angular 13 from time to time componet UI is broken - no errs in the console

### ISSUE THREAD

**Issue by cmester** [h2qutc/angular-material-components#269]
From time to time some users are experiencing this issue (Mac or Windows - latest chrome versions, Angular 13)

![image](https://user-images.githubusercontent.com/2271195/171564664-b05aad08-f92a-4d06-b568-8847fbaa1197.png)

Issue dissapears after hard refresh. 

Anybody experienced a similar issue, is there a workaround?

**Comment by kaihenzler** [comment]
+1

**Comment by h2qutc** [comment]
@cmester I will try to release a new version as soon as possible. Thanks to your support.

**Comment by johnbu2** [comment]
Any updates as to when this issue will be resolved?

**Comment by shanu-1119** [comment]
Hi @cmester  @johnbu2  @kaihenzler,

can u try  adding the below css

.mat-calendar-body-cell {
position: relative !important;
}

**Comment by ni3tzsch3** [comment]
![image](https://user-images.githubusercontent.com/31993641/181043798-ebce6b4d-6a95-4a92-b88e-27179b3a2316.png)


+1

angualar 14.0.5 - v 8.0.0

**Comment by shanu-1119** [comment]
Hi @cmester @ni3tzsch3 ,

can u try adding this css

.mat-calendar-body-cell {
    position: relative !important;
}

**Comment by cmester** [comment]
Hi

adding the proposed workaround is breaking standard <mat-datepicker>
component

[image: image.png]

Removed the  !important, and now <mat-datepicker> is displayed fine.
On the other hand I don't know if it will also fix
the <ngx-mat-datetime-picker> errors.

.mat-calendar-body-cell {
    position: relative;
}

**Comment by Sergiobop** [comment]
There are multiple style errors, caused by conflict with the styles of the standard mat-datepicker. 

I can reproduce them easily when i have a datetime picker and a standard datepicker (in the same view).
When you open the datetimepicker, then the standard datepicker, you can see a problem in mat-calendar-arrow caused by borders, and then, if you open the datetimepicker again, all styles are messed up (as you guys mentioned in this issue).

I spent some time trying to fix these issues, and as a workaround, add this to your styles.scss:
```css
.mat-calendar-arrow {
  border: none !important;
  width: 10px !important;
  height: 5px !important;
}
ngx-mat-calendar-header .mat-calendar-arrow {
  border-left: 5px solid transparent !important;
  border-right: 5px solid transparent !important;
  border-top-width: 5px !important;
  border-top-style: solid !important;
  width: 0 !important;
  height: 0 !important;
}
ngx-mat-month-view .mat-calendar-body-cell {
  position: relative !important;
}
```

All issues gone! 

Maybe the solution is wrap the datetimepicker styles inside a class, to not mess with the native styles.

FYI @cmester @ni3tzsch3 @johnbu2 @h2qutc @kaihenzler
