### ISSUE TITLE
Transparent background in popup

### ISSUE THREAD

**Issue by cperezabo** [h2qutc/angular-material-components#348]
Hi, I updated Angular and Material to v16.2.0 and datetime-picker to v16.0.1
I don't know what changed, but I'm getting a transparent background now. Any idea? 
<img width="468" alt="CleanShot 2023-08-14 at 18 59 08@2x" src="https://github.com/h2qutc/angular-material-components/assets/3604722/68cae2c4-05a7-4933-af16-70cf31eb6bfc">

Edit: In fact, confirmation button is missing, the popup won't close and there are no errors in console.

**Comment by AdamsContreras999** [comment]
yes for me is too same error

**Comment by cperezabo** [comment]
I updated from v9 to v16, so I don't know if this was working in v15. I would like to find where it broken

**Comment by AdamsContreras999** [comment]
in fact when all the angular dependencies were in version 16.1.0 it was working fine but angular was updated to version 16.2.0 and there it presented this error.

**Comment by tfiil** [comment]
I have also experienced the same issue after the upgrade.

However something strange I've noticed is that if I click a "normal" mat-datepicker in the same application and subsequently click the ngx-mat-datetime-picker it will be styled correctly. 

If no normal datepicker pop-up has been previously shown it will be transparent.

**Comment by cperezabo** [comment]
Maybe the issue comes from Material? I haven't got time to debug it deeply. But by what you say seems that the problem can come from upstream

**Comment by francobasilico** [comment]
There are some updates on 16.2.1.
https://github.com/angular/components/commit/0c4f947cdf511750b2e62f793e23b6bcc5678ab5#diff-70165fe5f110c97706ce01e94ddf46c6aad553a1c6948dabcd60b14ad6d734b6
Maybe this fix it, will try to give it a go soon

**Comment by francobasilico** [comment]
I quickly tried it persists in 16.2.1

**Comment by serg-mois-capital** [comment]
Faced the same problem. Does anybody have any workaround? It's a critical issue.

**Comment by cperezabo** [comment]
As a workaround I've added some styles globally, not all of them but enough for what I need in the meantime.


```scss
.mat-datepicker-content {
  box-shadow: 0 2px 4px -1px #0003, 0 4px 5px #00000024, 0 1px 10px #0000001f;
  background-color: #fff;
  color: #000000de
}

.mat-calendar-body-selected {
  background-color: #007f51;
  color: #fff;
}

.mat-calendar-body-cell-content {
  border: none !important;
}
```
