### ISSUE TITLE
Resizing issues with actions

### ISSUE THREAD

**Issue by iamkinetic** [h2qutc/angular-material-components#352]
You can use your own example (Datetime picker with actions buttons) to reproduce the bug: 

https://h2qutc.github.io/angular-material-components/#/datetimepicker

On some resolution, the dialog is incorrectly resized which makes the buttons float under the dialog like so : 

![image](https://github.com/h2qutc/angular-material-components/assets/21369128/5b557f14-aa0d-4000-b6f3-10f67e051f2c)

**Comment by iamkinetic** [comment]
The max-height in this css seems to be the problem: 
```css
.mat-datepicker-content-touch .mat-datepicker-content-container {
    min-height: 312px;
    max-height: 815px;
    min-width: 250px;
    max-width: 750px;
}
```
If i remove it, the dialog seems to be correctly displayed.
